language: node_js

node_js:
  - "14"

services:
  - postgresql

cache:
  directories:
    - node_modules

install:
  - npm ci

before_script:
  - psql -c 'CREATE DATABASE test;' -U postgres
  - sleep 10

script:
  - npm run test
