version: "3.8"
services:
  postgres:
    image: "postgres:13"
    container_name: postgres
    restart: always
    labels:
      "autoheal": "true"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - /mnt/data/nodejs-boilerplate/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USERNAME}"]
      interval: 1m
      timeout: 10s
      retries: 3
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
    ports:
      - "${PG_ADMIN_PORT}:80"
    volumes:
      - /mnt/data/nodejs-boilerplate/pgadmin:/var/lib/pgadmin
  api:
    build: .
    container_name: nodejs-boilerplate
    restart: always
    depends_on:
      - postgres
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - TOKEN_EXPIRES_IN=${TOKEN_EXPIRES_IN}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - LOG_GENERAL=${LOG_GENERAL}
      - LOG_QUERIES=${LOG_QUERIES}
      - LOG_ERRORS_DB=${LOG_ERRORS_DB}
      - LOG_ERRORS_CONSOLE=${LOG_ERRORS_CONSOLE}
      - LOG_REQUESTS_DB=${LOG_REQUESTS_DB}
      - LOG_REQUESTS_CONSOLE=${LOG_REQUESTS_CONSOLE}
    ports:
      - "${PORT}:${PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/v1/system/healthcheck"]
      interval: 1m
      timeout: 10s
      retries: 3
