version: "3.8"
services:
  postgres:
    image: "postgres:13"
    container_name: postgres-test
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ~/mnt/data/nodejs-boilerplate/pgdata:/var/lib/postgresql/data
